server:
  port: 8200

soul:
  springcloud:
    admin-url: http://192.168.1.99:9095
    context-path: /user
spring:
  application:
    name: soul-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.99:8848 #本次单机