server:
  port: 8200
  shutdown: graceful
spring:
  application:
    name: alibaba-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #本次单机
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.105.222.40:3306/t_test1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #保证插入的时间不会少8小时,取出来少8小时
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"