server:
  port: 8300

spring:
  application:
    name: dubbo-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.105.222.40:3306/seata_goods?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #保证插入的时间不会少8小时,取出来少8小时
    username: root
    password: root
  redis:
    cluster:
      nodes:
        - 47.105.222.40:7001
        - 47.105.222.40:7002
        - 47.105.222.40:7003
        - 47.105.222.40:7004
        - 47.105.222.40:7005
        - 47.105.222.40:7006
nacos: #必须配置
  host: 192.168.1.99
  port: 8848


dubbo:
  registry:
    address: nacos://192.168.1.99:8848
  scan:
    base-packages: com.demo.service #必须配置,否则无法调用成功 ,生产者
  protocol:
    name: dubbo
    port: -1

seata:
  application-id: applicationName
  tx-service-group: my_test_tx_group
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  service:
    #    vgroup-mapping:
    #      my_test_tx_group: default #默认
    grouplist:
      default: 192.168.1.99:8091
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.99:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.99:8848
      group : "SEATA_GROUP"
      username: ""
      password: ""
management:
  endpoints:
    web:
      exposure:
        include: "*"
