server:
  port: 9700
  shutdown: graceful
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: seata-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.30:8848 #本次单机
    sentinel:
      transport:
        dashboard: 192.168.1.31:8080
        client-ip: 192.168.1.5
      eager: true
      datasource:
        ds2:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-sentinel
            # group-id: DEFAULT_GROUP #默认
            # data-type: json #默认json
            rule-type: degrade

#  datasource: #整合到nacos配置
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://192.168.1.5:3306/t_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #保证插入的时间不会少8小时,取出来少8小时
#    username: root
#    password: root
#  redis: #整合到nacos配置
#    cluster:
#      nodes:
#        - 192.168.1.31:7001
#        - 192.168.1.31:7002
#        - 192.168.1.31:7003
#        - 192.168.1.31:7004
#        - 192.168.1.31:7005
#        - 192.168.1.31:7006

logging:
  level:
    com.alibaba.nacos.client.config.impl.ClientWorker: WARN #禁用nacos的刷屏

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
    max-connections: 1000
    max-connections-per-route: 100
  compression:
    request:
      enabled: true
    response:
      enabled: true


seata:
  application-id: applicationName
  tx-service-group: my_test_tx_group
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
#  service:#可在nacos配置
#    #    vgroup-mapping:
#    #      my_test_tx_group: default #默认
#    grouplist: # 可从nacos获取
#      default: 192.168.1.5:8091
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.30:8848
      # group: SEATA_GROUP #默认SEATA_GROUP
      # username: ""
      # password: ""
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.1.30:8848
      # application: seata-server
      # group : SEATA_GROUP #默认SEATA_GROUP
      # username: ""
      # password: ""
