server:
  port: 9700
  shutdown: graceful
spring:
  application:
    name: seata-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.99:8848 #本次单机
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.105.222.40:3306/seata_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #保证插入的时间不会少8小时,取出来少8小时
    username: root
    password: root
  redis:
    cluster:
      nodes:
        - 192.168.1.10:7001
        - 192.168.1.10:7002
        - 192.168.1.10:7003
        - 192.168.1.10:7004
        - 192.168.1.10:7005
        - 192.168.1.10:7006
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 50
    database: 1


management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  compression:
    response:
      enabled: true
    request:
      enabled: true

seata:
  application-id: applicationName
  tx-service-group: my_test_tx_group
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
#  service:#可在nacos配置
#    #    vgroup-mapping:
#    #      my_test_tx_group: default #默认
#    grouplist: # 可从nacos获取
#      default: 192.168.1.5:8091
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.99:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.99:8848
      group : "SEATA_GROUP"
      username: ""
      password: ""
