server:
  port: 9700
  shutdown: graceful
spring:
  application:
    name: seata-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.99:8848 #本次单机
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.105.222.40:3306/seata_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #保证插入的时间不会少8小时,取出来少8小时
    username: root
    password: root
  redis:
    cluster:
      nodes:
        - 47.105.222.40:7001
        - 47.105.222.40:7002
        - 47.105.222.40:7003
        - 47.105.222.40:7004
        - 47.105.222.40:7005
        - 47.105.222.40:7006
    jedis:
      pool:
        max-active: -1


management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  compression:
    response:
      enabled: true
    request:
      enabled: true

seata:
  application-id: applicationName
  tx-service-group: my_test_tx_group
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  service:
#    #    vgroup-mapping:
#    #      my_test_tx_group: default #默认
    grouplist:
      default: 192.168.1.5:8091
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.99:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.99:8848
      group : "SEATA_GROUP"
      username: ""
      password: ""
