server:
  port: 9000
  shutdown: graceful
spring:
  application:
    name: alibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #本次单机
    gateway:
      routes:
        - id: order-route
          uri: lb://alibaba-order
          predicates:
            - Path=/order/**
        - id: user-route
          uri: lb://alibaba-user
          predicates:
            - Path=/user/**
management:
  endpoints:
    web:
      exposure:
        include: "*"