server:
  port: 8100

spring:
  application:
    name: dubbo-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.105.222.40:3306/seata_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #保证插入的时间不会少8小时,取出来少8小时
    username: root
    password: root
nacos: #必须配置
  host: 192.168.1.99
  port: 8848

dubbo:
  registry:
    address: nacos://192.168.1.99:8848 #消费值

seata:
  application-id: applicationName
  tx-service-group: my_test_tx_group
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  service:
    #    vgroup-mapping:
    #      my_test_tx_group: default #默认
    grouplist:
      default: 192.168.1.99:8091
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.99:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.99:8848
      group : "SEATA_GROUP"
      username: ""
      password: ""
management:
  endpoints:
    web:
      exposure:
        include: "*"