server:
  port: 8600
  shutdown: graceful
  undertow:
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: rocketmq-push
rocketmq:
  name-server: 192.168.1.30:9876
  producer:
    group: my-group


