server:
  port: 8600
  shutdown: graceful
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.1.10:9876
        bindings:
          output:
            producer:
              group: test

