server:
  port: 9000
  shutdown: graceful
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: alibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.30:8848 #本次单机
        enabled: true
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: 192.168.1.31:8080
        client-ip: 192.168.1.5
      eager: true
      datasource:
        ds2:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: sentinel
            group-id: DEFAULT_GROUP
            # data-type: json
            rule-type: degrade

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      routes: # nacos动态化
#        - id: order-route
#          uri: lb://alibaba-order
#          predicates:
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.alibaba.nacos.client.config.impl.ClientWorker: WARN #禁用nacos的刷屏