server:
  port: 9000
  shutdown: graceful
spring:
  application:
    name: alibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.99:8848 #本次单机
        enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      routes: # nacos动态化
#        - id: order-route
#          uri: lb://alibaba-order
#          predicates:
#            - Path=/order/**
#        - id: user-route
#          uri: lb://alibaba-user
#          predicates:
#            - Path=/user/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.alibaba.nacos.client.config.impl.ClientWorker: WARN