server:
  port: 9000
  shutdown: graceful
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: alibaba-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      routes: # nacos动态化
#        - id: order-route
#          uri: lb://alibaba-order
#          predicates:
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.alibaba.nacos.client.config.impl.ClientWorker: WARN #禁用nacos的刷屏