server:
  port: 9600
  shutdown: graceful
  undertow:
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: seata-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.99:8848 #本次单机
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.99:3306/seata_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #保证插入的时间不会少8小时,取出来少8小时
    username: root
    password: root
  redis:
    cluster:
      nodes:
        - 192.168.1.10:7001
        - 192.168.1.10:7002
        - 192.168.1.10:7003
        - 192.168.1.10:7004
        - 192.168.1.10:7005
        - 192.168.1.10:7006
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 50
    database: 2
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
    max-connections: 1000
    max-connections-per-route: 100
  compression:
    request:
      enabled: true
    response:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
seata:
  application-id: applicationName
  tx-service-group: my_test_tx_group
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
#  service:#可在nacos配置
#    #    vgroup-mapping:
#    #      my_test_tx_group: default #默认
#    grouplist:
#      default: 192.168.1.99:8091
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.99:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.99:8848
      group : "SEATA_GROUP"
      username: ""
      password: ""
